### ISSUE TITLE
Jenkins: Add environment variable for CF_HOME

### ISSUE THREAD

**Issue by anwarchk** [spring-cloud/spring-cloud-pipelines#102]
From our experience, we have seen that when multiple Jenkins job runs at the same, there is a race condition on CF logged in state. To avoid this, if we could set a `CF_HOME` env variable, which can be localized to the workspace of a specific job, we could avoid the race condition. We experimented with this and seems to avoid the race condition.

**Comment by marcingrzejszczak** [comment]
For kubernetes it's `KUBECTL_BIN` and for CF it's `CF_BIN`

**Comment by marcingrzejszczak** [comment]
fixed by https://github.com/spring-cloud/spring-cloud-pipelines/commit/402f3da84e3f02630057ccd4c114e8705306ccf1

**Comment by anwarchk** [comment]
@marcingrzejszczak so we use `CF_BIN` instead of `CF_HOME` ?

**Comment by marcingrzejszczak** [comment]
Yeah but i can change the var name of it is important

**Comment by anwarchk** [comment]
No big deal, I just wanted to make sure that my understanding about the variable is correct
