### ISSUE TITLE
Github : Please create a new release from current master

### ISSUE THREAD

**Issue by anwarchk** [spring-cloud/spring-cloud-pipelines#103]
@marcingrzejszczak As of 10/11/2017, the `master` branch seems to be stable enough for us to work with. Can you please create a release from the master so that we can pin our pipeline to that tag

**Comment by marcingrzejszczak** [comment]
We'll release m7 once concourse is done too

**Comment by anwarchk** [comment]
@marcingrzejszczak are we close to a release ?

**Comment by marcingrzejszczak** [comment]
Yes :P
