### ISSUE TITLE
rollback smoke test run the latest tests and not the old ones

### ISSUE THREAD

**Issue by regevbr** [spring-cloud/spring-cloud-pipelines#118]
The docs clearly states that "we’re running the old smoke tests against the freshly deployed application surrounded by stubs"  and for a good reason but it seams that the implementation runs the tests of the latest repo state and not the latest release state.
I believe this can easily resolved by performing git branch command before running the tests.
@marcingrzejszczak what do you say?

**Comment by marcingrzejszczak** [comment]
Until now it was Jenkins or Concourse that took care of that. Are you running this from Bash only? If that's the case then indeed one would have to fetch the latest tags. Did I understand the issue correctly?

**Comment by regevbr** [comment]
Sorry im talking about the bash only version of the concrouse implementation.
There is no code there that fetches that tag it just realizes the tag name e,.g. prod/1.0.2 and uses it to deploy the app again in CF but it doesnt checkout that branch to run the tests of that version

**Comment by marcingrzejszczak** [comment]
That's a very good catch! In Jenkins it works fine https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/jenkins/jobs/jenkins_pipeline_sample.groovy#L444 but I don't see an equivalent in Concourse. We should indeed check out that version's code before running the rollback tests
