### ISSUE TITLE
change concourse pipeline version handling to the semver resource

### ISSUE THREAD

**Issue by regevbr** [spring-cloud/spring-cloud-pipelines#119]
The semver resource is much more intuitive and reduces redundant code and configurations that is required for handling the verisons

**Comment by marcingrzejszczak** [comment]
This sounds interesting. Care for a PR? :)

**Comment by regevbr** [comment]
Ill try and give it a go

**Comment by regevbr** [comment]
We need to rethink the way you use versions currently as you keep it 1.0.0 forever and just change the time stamp and semvar doesn't work that way as far as i understand. And if we change it it will conflict with the jenkins way. Suggestions?

**Comment by marcingrzejszczak** [comment]
So maybe let's leave this until this is done - https://github.com/spring-cloud/spring-cloud-pipelines/issues/94 . 

In your pipeline, until then, you can use the semver resource and ensure that the generated version is stored in a file that follows this convention

```
echo "Retrieving version"
cp "${ROOT_FOLDER}/${VERSION_RESOURCE}/version" "${SCRIPTS_OUTPUT_FOLDER}"/
export PIPELINE_VERSION
PIPELINE_VERSION="$( cat "${SCRIPTS_OUTPUT_FOLDER}/${VERSION_RESOURCE}" )"
echo "Retrieved version is [${PIPELINE_VERSION}]"
```

**Comment by regevbr** [comment]
OK,
And my pipeline already uses it and since we diverted from this project we changed a lof of conventions to match our needs but we took all the suggestions if the pipeline and really love it - this makes our ci much more safe and reliable ao thank you for that!

**Comment by marcingrzejszczak** [comment]
That's so great to hear :) If you have any feedback just ping me! I'll close this in favour of https://github.com/spring-cloud/spring-cloud-pipelines/issues/94
