### ISSUE TITLE
utuilize the keyval resource in the concourse pipeline

### ISSUE THREAD

**Issue by regevbr** [spring-cloud/spring-cloud-pipelines#120]
The keyval resource - https://github.com/SWCE/keyval-resource is a very convenient way to pass key values between jobs in the pipeline and can ease up passing data between the jobs instead of querying CF each step for example.

**Comment by marcingrzejszczak** [comment]
Which key / value pairs are you referring to?

**Comment by regevbr** [comment]
For example in my pipeline I pass along the stub runner url and test env url from job to job using that resource. Also I pass the latest prod tag and other data that I compute along the way to refrain from computing it again... (we don't use CF but have something similar of our own) We also use it to pass state between jobs etc.

**Comment by marcingrzejszczak** [comment]
I understand. At some point we did the same with Jenkins but we've decided to follow the Concourse philosophy of stateless jobs. That's why we don't pass these values between any steps.

**Comment by regevbr** [comment]
I understand but in practice you do have a state
When you split for example the steps of running smoke tests in CF you have a state of the deployed application in CF which is shared between the jobs...

**Comment by marcingrzejszczak** [comment]
Yeah, there is a state but it doesn't have to be passed. That way you can run a single step (for example from bash) and the only inputs are the general ones, not the ones that come from previous jobs.

**Comment by regevbr** [comment]
I hear what you are saying but I don't understand how is that "better" than passing it along?
For example I created the keyval-resource because we had to use it as we couldn't and wouldn't want to save the state externally

**Comment by marcingrzejszczak** [comment]
I'm not saying that it's "better" but I don't see it fix any problems now and from the point of Spring Cloud Pipelines support, I don't have to play around with different ways of doing the same thing (Jenkins DSL, Jenkinsfile and Concourse). 

However, we could change the code to try to get certain things from env vars and if they are not there we could try to fetch them. That way whatever you pass via the resource would take precedence.

**Comment by regevbr** [comment]
I see your point and since i don't know how jenkins pipelines work ill take your word for it but your suggestion makes sense!

**Comment by marcingrzejszczak** [comment]
Can you provide the full list of keys and values you're currently passing?

**Comment by regevbr** [comment]
Sure but i diverted a bit from this  project as we don't use CF. I'll send it tomorrow when I get back to the office

**Comment by regevbr** [comment]
PASSED_APPLICATION_URL - the url of the deployed test/stage env
PASSED_LATEST_PROD_VERSION - the latest produciton version
PASSED_REPO_PATH - the path to the repo (used internally by us)
PASSED_REPO_TAG - the tag used for the current version e.g. dev/0.0.1

**Comment by marcingrzejszczak** [comment]
in our case `PASSED_REPO_TAG` - that's not necessary since the CI takes care of this. But `PASSED_APPLICATION_URL` and `PASSED_LATEST_PROD_VERSION` - those could come in as an env var and if it's not there it could be repicked. Actually the last one already is an env var - https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/test_rollback_deploy.sh#L14 . 

Thanks for the feedback and we want more of it :D

**Comment by regevbr** [comment]
Thanks for adding that @marcingrzejszczak !

**Comment by marcingrzejszczak** [comment]
It was @ciberkleid that added this :) you're welcome anyways ;)

**Comment by ciberkleid** [comment]
Regev - thanks for all of the feedback you've provided so far. Please keep
it coming!! It is extremely valuable and very much appreciated.

On Sat, Dec 9, 2017 at 2:19 PM, Marcin Grzejszczak <notifications@github.com

**Comment by regevbr** [comment]
:-)
