### ISSUE TITLE
artifactory releases management question

### ISSUE THREAD

**Issue by regevbr** [spring-cloud/spring-cloud-pipelines#122]
Hi,

I'm trying to figure out why you publish to artifactory to a single repository without separation between production and development builds.

What we thought about doing is publish in the build stage to a snapshot repository and if it passes the pipeline and we decide to push it to production, copy the snapshot artifact to the releases artifactory repository and in all our testings and code dependencies we will always reference the latest release versions.

We think this is required as project A can start a pipeline with a successful build (and as such publish to artifactory) and then fail in smoke tests for example. We don't want other builds and tests to use the artifact as it is unstable. With the suggestion above, this issue does not exist.

@marcingrzejszczak can you please enlighten us?

**Comment by marcingrzejszczak** [comment]
> I'm trying to figure out why you publish to artifactory to a single repository without separation between production and development builds.

That's the idea of continuous delivery. Every merge to master results in the creation of an artifact that can (will) be deployed to production.

> What we thought about doing is publish in the build stage to a snapshot repository and if it passes the pipeline and we decide to push it to production, copy the snapshot artifact to the releases artifactory repository and in all our testings and code dependencies we will always reference the latest release versions.

That's a well-known approach in which you've got release branches etc. Git flow is one of such approaches. We have an issue to add support for such an approach (https://github.com/spring-cloud/spring-cloud-pipelines/issues/94)

> We think this is required as project A can start a pipeline with a successful build (and as such publish to artifactory) and then fail in smoke tests for example. We don't want other builds and tests to use the artifact as it is unstable. With the suggestion above, this issue does not exist.

With the approach in which every artifact can be deployed to production you won't have such a problem either. If the binary of other services is broken it will not pass the test / stage so you won't go with it to production. The very idea that any merge to master may (will) result in production deployment is a real eye-opener for the developers in terms of keeping the quality high.

**Comment by ezraroi** [comment]
Hi @marcingrzejszczak , but we publish the artifact in the build step... and the pipeline might fail in one of the next steps such as smoe, e2e, api competability or any other step... and in such cases.. we have publish artifact in our repo which didn't pass the whole pipeline.

This artifact can now be used as stubs or not stubs in their own pipelines...

**Comment by marcingrzejszczak** [comment]
Yeah, that's true. So if you've done a breaking change you will break all the other apps. That's life ;) If the developers know that they can break everybody else then they have to think twice before doing any changes. We are pushing towards immediate feedback. 

Does it make any sense? :P

**Comment by ezraroi** [comment]
this is true... but if it is not an api breaking change but smoke or e2e tests are failing... this artifact is still out there to be used... for api breaking changes you are right, but what about functional bug that will be cached only in e2e?

Also, if you broke your api... you will fail your pipeline.. but why you need to make noise to many other teams and services?

**Comment by marcingrzejszczak** [comment]
>but if it is not an api breaking change but smoke or e2e tests are failing... this artifact is still out there to be used... for api breaking changes you are right, but what about functional bug that will be cached only in e2e?

actually, with the current pipeline, you will not reach test cause you will break on API compatibility check

> for api breaking changes you are right, but what about functional bug that will be cached only in e2e?

what about it?  E2e is the place to test if all apps are working well together. That's the very essence of it. We want to do continuous integration and delivery so people must merge their code frequently. There are a lot of missing pieces, there are possibilities that things will blow up. We embrace that and have to make a pragmatic decision of whether we want to risk some problems of potentially faulty jars, or not.

> Also, if you broke your API... you will fail your pipeline.. but why you need to make noise for many other teams and services?

If you don't break the compatibility you will not make the noise. If however, you don't allow people to test if the dev versions work fine with other apps you will only get to know about this in e2e. 

I'm accepting the risk of breaking other people's work (which is minimal cause you can test the API compatibility locally) in favor of gaining pace of releasing features. If that's not acceptable to you or the gains are not as big as the noise then you shouldn't follow this convention. There are already companies that follow this approach and they're happy with the results. I know that @jkubrynski follows it so he can also present his opinion too.

**Comment by ezraroi** [comment]
Thanks for the detailed answers. We are trying to move our organization to CD and we are adopting this project. We ask the questions because some of the stuff was not complicity clear to us. 

Our main concern was that we are publishing an artifact to the main repo in very early stage without the confidence that smoke and e2e are passing. I do agree that if you pass unit and integration tests you have some confidence in the artifact. 

As we are trying to convince our management to move to CD from 6 weeks release which is our current methodology, we are being questioned many questions and need to fight many fights to prove that CD will improve our quality and feedback style. It will be great to hear others opinions and experience as this might help us reduce the panic :)

**Comment by jkubrynski** [comment]
@ezraroi  What do you mean by "make noise for other team or services"?

**Comment by jkubrynski** [comment]
The solution to fully encapsulate the delivery process is to use **multilevel staging**, where you promote the uploaded artifact between stages. For example, you upload the artifact in the first step (Build and upload) and then you promote it to stage "API checked" after running compatibility check. Then you can promote it one more time for example after finishing tests on "Test" environment to the stage "Rollback checked". Then you run E2E tests and promote it to the "Production" repository. You can promote by simply extending the particular build steps or using Maven profiles.

It's possible with the Nexus 2 and you can read more about that here: https://help.sonatype.com/display/NXRM2/Managing+Staging+Repositories#ManagingStagingRepositories-MultilevelStagingandBuildPromotion

**Comment by marcingrzejszczak** [comment]
The approach presented by @jkubrynski is the most "secured" one. Meaning, that you promote only the artifacts that have passed the necessary checks. That requires on the other hand some additional ops work in Nexus and build customization too (which is not a bad thing of course but takes time and effort).

The current presented solution is a balance between the ops effort and the acceptable level of security. It's similar to the approach presented here with zero downtime deployment https://spring.io/blog/2016/05/31/zero-downtime-deployment-with-a-database . It's the simplest solution but not the most bullet proof. 

So knowing all pros and cons it's up to you to decide what you want to do :) Also sc-pipelines should be extensible enough to pass your own approaches with minimal effort (hopefully) ;)

**Comment by ezraroi** [comment]
Thanks all... And it is extensible as we already customized it

**Comment by marcingrzejszczak** [comment]
Cool. You could write what you had to customize and how. That way maybe we could automate that customization?

**Comment by ezraroi** [comment]
Sure, once we will have the complete pipeline. We already added the key value resource. We will write, thanks

**Comment by marcingrzejszczak** [comment]
Ok I'll close this issue for now then
