### ISSUE TITLE
docker-lib.sh & spring-cloud/pipeline-base

### ISSUE THREAD

**Issue by pawelkalbrun** [spring-cloud/spring-cloud-pipelines#132]
Looks like start_docker has been removed in this [commit](https://github.com/spring-cloud/pipeline-base/commit/76e025c1debe3260d14ee8f08f58d33058872729#diff-e18927ace5713c51e33f595bd7dbfec2)

Concourse tasks are still referencing that function, unless I miss something?
source /docker-lib.sh 
start_docker

**Comment by marcingrzejszczak** [comment]
Wow, that's pathetic. Will fix it asap

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/spring-cloud/pipeline-base/commit/a45fe85c8d327edc086c59bba0581bce986d9077
