### ISSUE TITLE
The gitSsh credentials in Jenkins are not created

### ISSUE THREAD

**Issue by oiavorskyi** [spring-cloud/spring-cloud-pipelines#137]
The `gitSsh` credentials specification in Jenkins is not created due to the omission of the corresponding `ARG` in the `Dockerfile`.

**Comment by marcingrzejszczak** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-pipelines/commit/ee405c7d4b9b54db99d6727b7f1d8e463b2cd3b7
