### ISSUE TITLE
Scripts tests fail when specifying PIPELINE_DESCRIPTOR

### ISSUE THREAD

**Issue by oiavorskyi** [spring-cloud/spring-cloud-pipelines#142]
After specifying `PIPELINE_DESCRIPTOR` parameter in a seed pipeline to use PWS-specific file, the execution fails with `ok 154 sourcing pipeline.sh should export an env var with lower case env var` message. Also, many other tests output error messages without failing.

**Comment by marcingrzejszczak** [comment]
We've decided to create a separate CI job for the whole project. The seed jobs will be executed with test skipping.
