### ISSUE TITLE
[Jenkins] Download the pipeline definition instead of cloning it from Git

### ISSUE THREAD

**Issue by oiavorskyi** [spring-cloud/spring-cloud-pipelines#146]
Currently, each step in the pipeline clones common scripts from the Github repository. The credentials used to access the repository are the same as the Git credentials used to access the source project's repository. While acceptable for the sample projects and unmodified SCP sources, this is not a valid scenario in some corporate environments. Besides, there is no control of which version of the SCP is used. 

The proposal is to download release archive from the Git repo instead of cloning it.

**Comment by marcingrzejszczak** [comment]
Implemented for Jenkins Job DSL
