### ISSUE TITLE
Jenkins Pipeline Downloads Non-existant Artifacts From Artifactory

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-pipelines#15]
I have run into some scenarios (due to my own mistakes) where the Jenkins pipeline will try to download artifacts from Artifactory that do not exist.  Artifactory responds to these requests with some JSON response that has a 404 message in it.  However the scripts will then try to deploy these "jars" to CF but then CF fails to start them.  The end result is a very misleading error message from CF.  It would be nice if we could inspect what is saved when pulling Jars from Artifactory to make sure it is not a 404 JSON response.

**Comment by marcingrzejszczak** [comment]
I get it. Makes sense and that's really easy to fix
