### ISSUE TITLE
null in hostname

### ISSUE THREAD

**Issue by vanjan** [spring-cloud/spring-cloud-pipelines#171]
Hello, 

I'm following the tutorial using github-webhook with Concourse and PCF Dev.

When running the `test-deploy` step, the following routes are set up in PCF Dev:

- github-eureka-**null**-test-github-webhook.local.pcfdev.io
- github-eureka-**null**-test-github-webhook.local.pcfdev.io

It looks like the 'null' is coming from https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/pipeline-cf.sh#L362. I'm not sure why we need this suffix...

```
eploying app as service. Options - jar name [github-eureka-0.0.1.M1], app name [github-eureka], env [TEST], path to manifest [sc-pipelines/manifest-eureka.yml]
Project has artifact type [binary]
Deploying app with name [github-eureka], env [TEST] and host [github-eureka-null-test-github-webhook] with manifest file [sc-pipelines/manifest-eureka.yml]
Pushing from manifest to org pcfdev-org / space sc-pipelines-test-github-webhook as user...
Using manifest file sc-pipelines/manifest-eureka.yml
Getting app info...
Creating app with these attributes...
+ name:        github-eureka
  path:        /tmp/build/9f091a8c/repo/target/github-eureka-0.0.1.M1.jar
+ instances:   1
  services:
+   github-rabbitmq
  env:
+   APPLICATION_DOMAIN
+   DEBUG
+   SPRING_PROFILES_ACTIVE
  routes:
+   github-eureka-null-test-github-webhook.local.pcfdev.io
```

**Comment by marcingrzejszczak** [comment]
null comes from the fact that it wasn't set in the sample credentials. I guess we should put a guard for it...

Why do you need a suffix? When you deploy in a multitenant environment your hostname can be taken.
