### ISSUE TITLE
Credentials re-created

### ISSUE THREAD

**Issue by prumand** [spring-cloud/spring-cloud-pipelines#176]
I used some parts of your init script and found that https://github.com/spring-cloud/spring-cloud-pipelines/blame/master/jenkins/seed/init.groovy#L18 and https://github.com/spring-cloud/spring-cloud-pipelines/blame/master/jenkins/seed/init.groovy#L30 didn't work for my jenkins instance as expected. I replaced it with:
```
boolean credsMissing = SystemCredentialsProvider.getInstance().getCredentials().findAll {
  it.getId() == id
}.empty
```

**Comment by marcingrzejszczak** [comment]
Awesome. Care for a PR? :)

**Comment by prumand** [comment]
Sure (https://github.com/spring-cloud/spring-cloud-pipelines/pull/178).

A quick code search showed some other occurrences, which I changed as well.

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-pipelines/pull/178
