### ISSUE TITLE
Override the "deployService" function for all states of the flow

### ISSUE THREAD

**Issue by davsuapas** [spring-cloud/spring-cloud-pipelines#188]
I would like override the "deployService" function  for all states of the flow. I need add infrastructure services like Zuul, configuration, hystrix, etc.

I think that could be good include the pipeline-PAAS_TYPE.sh source into "custom" folder as bold code below. In this way the hook chain would be pipeline (master) / pipline (custom) / script (root).

```
[[ -f "${__ROOT}/pipeline-${PAAS_TYPE}.sh" ]] && source "${__ROOT}/pipeline-${PAAS_TYPE}.sh" ||  \
 echo "No pipeline-${PAAS_TYPE}.sh found"

**[[ -f "${__ROOT}/custom/pipeline-${PAAS_TYPE}.sh" ]] && source "${__ROOT}/custom/pipeline-${PAAS_TYPE}.sh" ||  \
 echo "No pipeline-${PAAS_TYPE}.sh custom found"**
```

**Comment by marcingrzejszczak** [comment]
Ha! That's a good idea, I like it!

**Comment by marcingrzejszczak** [comment]
@davsuapas Done! You can try the latest master.

BTW Can you ping me on http://gitter.im/ ? I'd like to have a private chat with you :)
