### ISSUE TITLE
Introduce Spinnaker pipelines

### ISSUE THREAD

**Issue by gregturn** [spring-cloud/spring-cloud-pipelines#25]
Create "Deploy to staging" and "Deploy to production" pipelines.

Deploy to staging should:

* Depend on a Jenkins build job for a trigger
* Leverage a Jenkins smoke test job
* Deploy using highlander strategy, presuming staging resources should be kept to a minimum.

Deploy to production should:

* Depend on deploy to staging pipeline as a trigger
* Use Find Image for artifact discovery, finding the newest server group
* Deploy using a red/black strategy with 2 server groups.

These jobs should presume user configures Spinnaker for a single CF space.

**Comment by gregturn** [comment]
Tracking this effort on https://github.com/gregturn/spring-cloud-pipelines/tree/gh-25

**Comment by marcingrzejszczak** [comment]
On hold. We'll come back to this if the community is interested in this.
