### ISSUE TITLE
Does the pipeline only supports PCF instance for now?

### ISSUE THREAD

**Issue by wangqingjiewa** [spring-cloud/spring-cloud-pipelines#61]
Does the pipeline only supports PCF instance for now? Any guide for how to  discover computing resource on K8s, Openstack or other platforms?

**Comment by marcingrzejszczak** [comment]
So currently we support CF out of the box. But it's easy to change. 

This function logs in to CF - https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/pipeline.sh#L7-L37 I guess you'll have to rename it and update it or even completely remove it. Of course, don't' forget to update other bash scripts.

These functions are about Rabbit & MySQL on CF - https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/pipeline.sh#L39-L68 you'll have to rename and update these

This function retrieves the host of an app via name - https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/pipeline.sh#L100-L105 - you'll need to update it

Here we have deletion, restarting and setting of env vars on apps - https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/pipeline.sh#L135-L163 - you'll need to update it

https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/pipeline.sh#L220-L233 - here we create user provided services and we bind applications to them. You'll have to update it

Here you have the code necessary for zero downtime deployment - https://github.com/spring-cloud/spring-cloud-pipelines/blob/master/common/src/main/bash/pipeline.sh#L488-L511 . You'll need to update it.

And that's basically it. It's not THAT terrible to customize but you'll need a little bit of work. Also if you do that PLEASE provide some feedback on what you had to do. That way it will be easier for me to do that one - https://github.com/spring-cloud/spring-cloud-pipelines/issues/55

**Comment by wangqingjiewa** [comment]
@marcingrzejszczak Thanks for guiding me on how to do the customisation. I am not do the custimazation for now, but do you have any roadmap to officially support K8s installation? Thanks!

**Comment by marcingrzejszczak** [comment]
Now we do https://github.com/spring-cloud/spring-cloud-pipelines/issues/63 :) I'll look into the steps that I defined here and go through the steps myself. That way I'll see if any abstractions didn't leak (and I already see that CF is all over the place...)
