### ISSUE TITLE
Caching mvn/gradle resources - in light of concourse 3.3.0

### ISSUE THREAD

**Issue by bijukunjummen** [spring-cloud/spring-cloud-pipelines#68]
The new concourse 3.3.0 introduces a feature (https://github.com/concourse/concourse/releases/tag/v3.3.0) where certain directories can be marked as cached, for subsequent runs the cached directory will be reused. With this new feature in place, I feel that the base custom image used with the concourse pipelines with cached resources can be changed to a generic image with java/maven/gradle in it

**Comment by marcingrzejszczak** [comment]
Yup - we will be doing a big rewrite of the Concourse stuff to use resources and caches. @nebhale will help me with that :) Thanks for the feedback and remember to check out this issue https://github.com/spring-cloud/spring-cloud-pipelines/issues/55 too :)

**Comment by nebhale** [comment]
Yep, just converted all of the Java Experience builds to use it and it's good.

**Comment by marcingrzejszczak** [comment]
Done in https://github.com/spring-cloud/spring-cloud-pipelines/pull/77
