### ISSUE TITLE
Update samples to use micrometer

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-pipelines#74]
http://micrometer.io/docs/prometheus#_spring_support

**Comment by jkschneider** [comment]
https://github.com/spring-cloud-samples/github-analytics/blob/master/src/main/java/org/springframework/github/IssuesService.java#L25

**Comment by marcingrzejszczak** [comment]
Fixed by https://github.com/spring-cloud-samples/github-analytics/commit/977b14edbaebe9eee8ea77ca67c5635cb66b2bc5 and https://github.com/spring-cloud-samples/github-analytics-kubernetes/commit/d4ad5463426e487124968a743e1e568b5b5d6383
