### ISSUE TITLE
Unable to create /usr/share/jenkins/gituser

### ISSUE THREAD

**Issue by pfrank13** [spring-cloud/spring-cloud-pipelines#9]
I was just trying to run through the documentation and try out the jenkins version of the demo and ran into this problem when trying to run 

./start.sh gitUser gitPass gitOrg

Obviously with my real credentials and what not in there and got this error during starting up the containers via docker-compose

/bin/sh: 1: cannot create /usr/share/jenkins/gituser: Permission denied
ERROR: Service 'jenkins' failed to build: The command '/bin/sh -c printf "%s" "${gituser}" > /usr/share/jenkins/gituser' returned a non-zero code: 2

Looking into the Dockerfile I added my credentials there as well (that's a documentation miss I think)

Tried again, same error, which isn't shocking because my change has nothing to do with permissions.

Using ROOT that error disappears, and the credentials appear in jenkins (which I think is all that's doing there) so it seems like a viable solution.

I'm using Mac OS X El Capitan, Docker for Mac 1.12.1, and Virtual Box 5.1.8

**Comment by marcingrzejszczak** [comment]
So as you can see in the dockerfile we're using ARGS. They are passed from Docker Compose. The script start.sh is passing the username and password via env vars to docker compose. Everything works smoothly. interesting why it's not working for you

**Comment by marcingrzejszczak** [comment]
> Looking into the Dockerfile I added my credentials there as well (that's a documentation miss I think)

This is obviously not the case cause the credentials are passed via args

**Comment by MarkMcCann1** [comment]
I too had this issue.  I resolved it by moving the declaration of "USER root" above the RUN commands in the DockerFile.


....
USER root

# Generated via start.sh
# If you don't want to provide it just put empty files there
RUN printf "%s" "${gituser}" > /usr/share/jenkins/gituser
RUN printf "%s" "${gitpass}" > /usr/share/jenkins/gitpass

# Moved to above the RUN commands.
# USER root

RUN apt-get update && apt-get install -y \
  ruby \
  curl

USER jenkins
....

**Comment by marcingrzejszczak** [comment]
Fixed
