### ISSUE TITLE
Add support for SSH based Git access from JenkinsFile Groovy script

### ISSUE THREAD

**Issue by anwarchk** [spring-cloud/spring-cloud-pipelines#98]
Currently, the pipeline only supports userid/pwd based authentication to talk to Git. It would be helpful to have support for SSH based authentication from the Groovy scripts.

**Comment by anwarchk** [comment]
This is also helpful for `2FA` enabled repositories

**Comment by anwarchk** [comment]
@marcingrzejszczak do you have a sample script on how to use this ?

**Comment by marcingrzejszczak** [comment]
You have to create the credential with the key by yourself. Call it e.g. Foo. Then in the seed job you can set the value of GIT SSH CRED ID to point to Foo. That way the pipeline will use the key for git

**Comment by marcingrzejszczak** [comment]
BTW, have you read the docs? :P http://cloud.spring.io/spring-cloud-pipelines/single/spring-cloud-pipelines.html#_using_ssh_keys_for_git

**Comment by anwarchk** [comment]
Just found about the update doc section...thanks ! This where release would help since we could just look into the release notes. :-)
